micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        enabled: true
        generator:
          refresh-token:
            enabled: true
          access-token:
            expiration: 1200
