micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: youHaveToChangeThisToANewOne.TrustMe.
        generator:
          refresh-token:
            secret: youHaveToChangeThisToANewOne.TrustMe.
